### ISSUE TITLE
Data blob's shape incompatible with training's data shape during testing.

### ISSUE THREAD

**Issue by omair18** [facebook/C3D#164] opened 2016-11-07 08:22 UTC
I trained my model using data shape = 10x1x32x32x32 in a hdf5 file (see 1st screenshot). But when I load my trained model in python using caffe.Net() and a deploy.prototxt file (screenshot 2) mentioning input_dim my data blob's shape returned is 10x1x32x32 which is a 4D vector whereas data loaded at the time of training was a 5D vector. 
Why is there such difference? How can I correct this problem?

![selection_007](https://cloud.githubusercontent.com/assets/1974232/20050744/cf4d5834-a4ec-11e6-8f6b-92f2926ca71d.png)
![selection_009](https://cloud.githubusercontent.com/assets/1974232/20050769/e9343d58-a4ec-11e6-89fc-de247b85986b.png)
![selection_008](https://cloud.githubusercontent.com/assets/1974232/20050773/ec9219fc-a4ec-11e6-940c-1bcd0fd438f1.png)

**Comment by dutran** [comment] 2016-11-08 01:02
First question: in training, you have input 
[data] = 10x1x32x32x32 I read as mini-batch =10 examples, channel=1, volume size = 32x32x32
[label] = 10x1x32x1x1 so that mean each label has size 1x32x1x1 what is that?

Could you point me to the python script you used? Is it https://github.com/facebook/C3D/pull/59, we haven't fully tested that PR yet. So potentially there are some dimension mismatch

**Comment by omair18** [comment] 2016-11-08 09:55
There was a slight mistake in hdf5_data_layer.cpp. Lable's blob was mistakenly reshaped to data blobs length size. I have resolved this error and now label shape is 10x1x1x1x1. 
I am simply loading Deploy.prototxt and trained model in caffe.Classifier() and trying to input data using net.forward(data= inputdata) function. 
![selection_075](https://cloud.githubusercontent.com/assets/1974232/20094484/3a1bd4d4-a5c3-11e6-828f-a7ebf01f8482.jpg)
![selection_074](https://cloud.githubusercontent.com/assets/1974232/20094485/3ae5bda8-a5c3-11e6-83da-df19ff552d5a.jpg)

**Comment by omair18** [comment] 2016-11-08 18:41
@dutran still having the same issue ( regarding data blob size ) even after correcting label's dimensions while training.  Any suggestion please?

**Comment by dutran** [comment] 2016-11-08 18:51
I think this issue caused by the python wrapper #163. So closing this and follow-up on the other issue.

**Closed by dutran** 2016-11-08 18:51 UTC
